name: dl

channels:
    - pytorch
    - conda-forge
    - defaults

dependencies:
    - python=3.7
    - numpy
    - mkl
    - jupyterlab
    - pandas
    - matplotlib
    - seaborn
    - pytorch
    - torchvision
    - scikit-learn